### ISSUE TITLE
License

### ISSUE THREAD

**Issue by johanmazel** [shybovycha/gantt-chart#5]
Hello
I would like to reuse some of your code for a project that will be on GitHub pages.

I think your code currently does not have any license.
Do you plan to keep your code as is? Or would it be possible for you to add an open source license (GPL-like or BSD-like are both OK for me)?

Best regards,
Johan

**Comment by shybovycha** [comment]
Hey,

Added an MIT license dating back 2020 (first commit date), so that you could use any version of the code.

Enjoy!

**Comment by johanmazel** [comment]
Thank you very much. :)
Best regards.
